name: Windows RDP via Tailscale

on:
  workflow_dispatch:
    inputs:
      authkey:
        description: 'Tailscale Auth Key'
        required: true
        type: string

jobs:
  rdp:
    runs-on: windows-latest
    
    steps:
    - name: Setup RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Runner2024!" -Force)
    
    - name: Install Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'tailscale.msi', '/quiet' -Wait
    
    - name: Connect Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ github.event.inputs.authkey }} --hostname=github-runner
    
    - name: Show Connection Info
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "========================================="
        Write-Host "RDP BAĞLANTI BİLGİLERİ:"
        Write-Host "========================================="
        Write-Host "Tailscale IP: $ip"
        Write-Host "Port: 3389"
        Write-Host "Kullanıcı: runneradmin"
        Write-Host "Şifre: Runner2024!"
        Write-Host "========================================="
    
    - name: Keep Alive
      run: Start-Sleep -Seconds 21600
