name: Windows RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "ActionRunner2024!" -Force)
    
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
    
    - name: Start Ngrok Tunnel
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=eu 3389"'
        Start-Sleep -Seconds 10
    
    - name: Get Ngrok URL
      run: |
        $response = Invoke-WebRequest -Uri http://localhost:4040/api/tunnels
        $json = $response | ConvertFrom-Json
        $tunnel = $json.tunnels[0].public_url
        
        Write-Host "========================================="
        Write-Host "RDP BAĞLANTI BİLGİLERİ:"
        Write-Host "========================================="
        Write-Host "Adres: $tunnel"
        Write-Host "Kullanıcı: runneradmin"
        Write-Host "Şifre: ActionRunner2024!"
        Write-Host "========================================="
        Write-Host ""
        Write-Host "NASIL BAĞLANILIR:"
        Write-Host "1. Windows: mstsc.exe açın"
        Write-Host "2. Bilgisayar: $($tunnel -replace 'tcp://', '')"
        Write-Host "3. Kullanıcı adı ve şifreyi girin"
        Write-Host "========================================="
    
    - name: Keep Alive
      run: |
        Write-Host "RDP bağlantısı hazır! 6 saat boyunca aktif kalacak..."
        Start-Sleep -Seconds 21600
