name: Windows RDP Access

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "ActionRunner2024!" -Force)
    
    - name: Create Tunnel 
      run: |
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\cloudflared.exe tunnel --url tcp://localhost:3389"'
        Start-Sleep -Seconds 10
    
    - name: Get Tunnel URL
      run: |
        $response = try { Invoke-RestMethod -Uri http://localhost:8080/metrics } catch { $null }
        if ($response) {
          Write-Host "Tunnel URL: Check cloudflared output"
        }
        
        Write-Host "========================================="
        Write-Host "RDP BAĞLANTI BİLGİLERİ:"
        Write-Host "========================================="
        Write-Host "Cloudflared çıktısını kontrol edin"
        Write-Host "URL formatı: https://xxxxx.trycloudflare.com"
        Write-Host ""
        Write-Host "Kullanıcı: runneradmin"
        Write-Host "Şifre: ActionRunner2024!"
        Write-Host "========================================="
        Write-Host ""
        Write-Host "BAĞLANTI TALİMATLARI:"
        Write-Host "1. Actions log'unda cloudflared çıktısını bulun"
        Write-Host "2. 'https://xxxxx.trycloudflare.com' şeklinde bir URL göreceksiniz"
        Write-Host "3. Bu URL'yi RDP client'ta kullanın"
        Write-Host "========================================="
    
    - name: Alternative - Direct IP Method
      run: |
        Write-Host ""
        Write-Host "ALTERNATİF YÖNTEM - Public IP:"
        $ip = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
        Write-Host "Public IP: $ip:3389"
        Write-Host "(Not: Bu IP direkt çalışmayabilir, firewall nedeniyle)"
    
    - name: Keep Alive
      run: |
        Write-Host ""
        Write-Host "Sistem 6 saat boyunca açık kalacak..."
        $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
        while ($stopwatch.Elapsed.TotalHours -lt 6) {
          Write-Host "Aktif süre: $([math]::Round($stopwatch.Elapsed.TotalMinutes)) dakika - $(Get-Date -Format 'HH:mm:ss')"
          Start-Sleep -Seconds 300
        }
